SRC += ckoehn.c

BACKLIGHT_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
ENCODER_ENABLE = no
LTO_ENABLE = yes
MIDI_ENABLE = no
MOUSEKEY_ENABLE = no
UNICODEMAP_ENABLE = yes
UNICODE_ENABLE = no
